# -*- coding: utf-8 -*-
"""data_retrieval.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nXwfB3ePqYt4aV0gAoq2pBEJb1lJo-OV
"""

# 1. Install necessary libraries
!pip install geemap

import ee
import geemap
import time

# 1. Authenticate and Initialize
ee.Authenticate()
MY_PROJECT_ID = input("Please enter your Google Cloud Project ID: ")
ee.Initialize(project=MY_PROJECT_ID)

# 2. Define Geography (Armenia Study Sites)
sites = {
    "Dilijan_North": [44.86, 40.74],
    "Syunik_South": [46.40, 39.20]
}

# 3. Define Seasons (Phenological Stages)
seasons = {
    "Summer_Peak": ['2023-07-01', '2023-08-31'],
    "Autumn_Senescence": ['2023-10-01', '2023-11-15'],
    "Winter_Dormancy": ['2024-01-01', '2024-02-28'],
    "Spring_Rebirth": ['2024-04-15', '2024-05-31']
}

# 4. Automated Retrieval Function
def export_forest_data(site_name, season_name, lon, lat, dates):
    # Create Region of Interest (ROI) - 5km buffer around point
    roi = ee.Geometry.Point(lon, lat).buffer(5000).bounds()

    # Filter Sentinel-2 Collection
    image = (ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
             .filterBounds(roi)
             .filterDate(dates[0], dates[1])
             .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 10)) # Slight increase to ensure data in winter
             .median()
             .clip(roi))

    # Select Bands (Red and NIR)
    # We multiply by 0.0001 to convert Sentinel-2 DN to Reflectance (0-1 range)
    export_img = image.select(['B4', 'B8']).multiply(0.0001).float()

    # Setup Export Task
    task_name = f"{site_name}_{season_name}"
    task = ee.batch.Export.image.toDrive(
        image=export_img,
        description=task_name,
        folder='Armenia_Forest_Project',
        fileNamePrefix=task_name,
        scale=10,
        region=roi,
        fileFormat='GeoTIFF'
    )
    task.start()
    print(f"Started task: {task_name}")

# 5. The Double Loop: Site x Season
print("Launching 8 export tasks to your Google Drive...")
for site_name, coords in sites.items():
    for season_name, dates in seasons.items():
        export_forest_data(site_name, season_name, coords[0], coords[1], dates)

print("\nAll tasks submitted. Check the 'Tasks' tab in GEE or your Google Drive folder 'Armenia_Forest_Project' in a few minutes.")